fix gha

diff --git a/.github/workflows/updates.yaml b/.github/workflows/updates.yaml
--- a/.github/workflows/updates.yaml
+++ b/.github/workflows/updates.yaml
@@ -45,7 +45,7 @@ jobs:
 
       - name: Update dependencies
         run: |
-          scala-cli --power dependency-update branch --all
+          scala-cli --power dependency-update src --all
           git config --global user.name "Mark Rudolph"
           git config --global user.email "mark@k8ty.app"
           git commit -am "Update dependencies" && echo "changes_exists=true" >> $GITHUB_ENV || echo "No changes to commit" && echo "changes_exists=false" >> $GITHUB_ENV
@@ -60,12 +60,12 @@ jobs:
             --title "Dependency Updates" \
             --body "Dependency updates from scala-cli" \
             --head dependency-update \
-            --base main && gh workflow run pr-tests.yml || echo "Pull request already exists or no changes to push"
+            --base main || echo "Pull request already exists or no changes to push"
 
       - name: Trigger PR Tests
         run: |
           if [ "$changes_exists" = "true" ]; then
-            gh workflow run pr-tests.yml  || echo "Error running PR tests"
+            gh workflow run pr-tests.yaml  || echo "Error running PR tests"
           else
             echo "No changes; not running PR tests"
           fi
